# Generated by Django 4.2.4 on 2023-10-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='theme',
            field=models.CharField(choices=[('SP', 'Спорт'), ('PO', 'Политика'), ('WE', 'Погода'), ('CU', 'Культура')], max_length=2, unique=True),
        ),
    ]
