# Generated by Django 4.2.7 on 2023-11-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_rating',
            new_name='rating',
        ),
    ]
